FROM python:3.11-slim
RUN apt-get update && apt-get install -y \
    strace \
    nodejs \
    npm \
    perl \
    ruby \
    bash \
    && rm -rf /var/lib/apt/lists/*
RUN mkdir -p /code
WORKDIR /code